---
- name: Testing andrewrothstein.yarn
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing command 'yarn --version'
      ansible.builtin.command: yarn --version
      changed_when: false
      register: yarn_test_output
    - name: Output from 'yarn --version'
      ansible.builtin.debug:
        msg: '{{ yarn_test_output.stdout }}'
